#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Extensions PR Build

on:
  workflow_call:
    inputs:
      changed:
        description: 'True if this module has been changed and should be rebuilt'
        required: true
        type: string
      wrapping-artifact-id:
        description: 'The Workflow Run ID of the last workflow containing artifacts for the wrapping module'
        required: true
        type: string
      gradle-artifact-id:
        description: 'The Workflow Run ID of the last workflow containing artifacts for the gradle module'
        required: true
        type: string
      maven-artifact-id:
        description: 'The Workflow Run ID of the last workflow containing artifacts for the maven module'
        required: true
        type: string
      framework-artifact-id:
        description: 'The Workflow Run ID of the last workflow containing artifacts for the framework module'
        required: true
        type: string

jobs:

  log-unchanged:
    name: Extensions is unchanged
    if: ${{ inputs.changed == 'false' }}
    runs-on: ubuntu-latest

    steps:
      - name: Log this module is unchanged
        run: |
          echo "The extensions module is unchanged"

  build-extensions:
    name: Build Extensions source code
    if: ${{ inputs.changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup JDK 
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'semeru'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9
          cache-disabled: true

      # For any modules that were changed in this PR,
      # download their artifacts from this workflow run.

      - name: Download wrapping artifacts from this workflow
        id: download-wrapping
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: wrapping
          path: modules/artifacts/dev/galasa

      - name: Download gradle artifacts from this workflow
        id: download-gradle
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: gradle
          path: modules/artifacts/dev/galasa

      - name: Download maven artifacts from this workflow
        id: download-maven
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: maven
          path: modules/artifacts/dev/galasa

      - name: Download framework artifacts from this workflow
        id: download-framework
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: framework
          path: modules/artifacts/dev/galasa

      # For any modules that weren't changed in this PR,
      # download artifacts from the last successful workflow.

      - name: Download wrapping artifacts from last successful workflow
        if: ${{ steps.download-wrapping.outcome == 'failure' }}
        uses: actions/download-artifact@v4
        with:
          name: wrapping
          path: modules/artifacts/dev/galasa
          github-token: ${{ github.token }}
          run-id: ${{ inputs.wrapping-artifact-id }}

      - name: Download gradle artifacts from last successful workflow
        if: ${{ steps.download-gradle.outcome == 'failure' }}
        uses: actions/download-artifact@v4
        with:
          name: gradle
          path: modules/artifacts/dev/galasa
          github-token: ${{ github.token }}
          run-id: ${{ inputs.gradle-artifact-id }}

      - name: Download maven artifacts from last successful workflow
        if: ${{ steps.download-maven.outcome == 'failure' }}
        uses: actions/download-artifact@v4
        with:
          name: maven
          path: modules/artifacts/dev/galasa
          github-token: ${{ github.token }}
          run-id: ${{ inputs.maven-artifact-id }}

      - name: Download framework artifacts from last successful workflow
        if: ${{ steps.download-framework.outcome == 'failure' }}
        uses: actions/download-artifact@v4
        with:
          name: framework
          path: modules/artifacts/dev/galasa
          github-token: ${{ github.token }}
          run-id: ${{ inputs.framework-artifact-id }}

      - name: Build Extensions source code with gradle
        working-directory: modules/extensions
        run: |
          gradle -b galasa-extensions-parent/build.gradle check publish --info \
          --no-daemon --console plain \
          -PsourceMaven=${{ github.workspace }}/modules/artifacts \
          -PcentralMaven=https://repo.maven.apache.org/maven2/ \
          -PtargetMaven=${{ github.workspace }}/modules/extensions/repo

      - name: Upload extensions artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extensions
          path: modules/extensions/repo/dev/galasa
          retention-days: 7